name:                morpheus-graphql-extensible
version:             0.1.0.0
github:              "charlescrain/morpheus-graphql-extensible"
license:             BSD3
author:              "Charles Crain"
maintainer:          "craincharles@gmail.com"
copyright:           "Pixura"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/charlescrain/morpheus-graphql-extensible#readme>

ghc-options: -Wall -Werror

dependencies:
- base >= 4.7 && < 5
- extensible >= 0.7.1
- morpheus-graphql >= 0.10.1
- template-haskell
- text


library:
  source-dirs: src
  default-extensions:
    - ApplicativeDo
    - BangPatterns
    - ConstraintKinds
    - DataKinds
    - DefaultSignatures
    - DeriveFoldable
    - DeriveFunctor
    - DeriveGeneric
    - DeriveLift
    - DeriveTraversable
    - DerivingStrategies
    - EmptyCase
    - ExistentialQuantification
    - FlexibleContexts
    - FlexibleInstances
    - FunctionalDependencies
    - GADTs
    - GeneralizedNewtypeDeriving
    - InstanceSigs
    - KindSignatures
    - LambdaCase
    - MultiParamTypeClasses
    - MultiWayIf
    - NamedFieldPuns
    - OverloadedStrings
    - OverloadedLabels
    - PatternSynonyms
    - RankNTypes
    - RecordWildCards
    - ScopedTypeVariables
    - StandaloneDeriving
    - TupleSections
    - TypeApplications
    - TypeFamilies
    - TypeFamilyDependencies
    - TypeOperators
    - TemplateHaskell

tests:
  morpheus-graphql-extensible-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - morpheus-graphql-extensible
